### PR TITLE
2 new words and the trademark symbol

### PR DESCRIPTION
**Pull request by KararTY**
Added "Harmful" as adjective, and "Opinions" as noun. Also added a new name template: <silly>™

### CODE REVIEW

**Comment by iguananaut** [comment]
Haha, thanks. I don't quite get the point of the trademark symbol but I think it technically will work and could be funny. 

This is a nitpick but I try to keep each category alphabetized so if you could move "Opinions" into the right location that'd be great.

**Comment by iguananaut** [comment]
Also you don't need to add "Harmful" twice. A kind of confusing aspect I'd like to rethink about the grammar but I don't really have time.

**Comment by KararTY** [comment]
Alrighty, there we go.

Armored/Armoured Skeptic was once very concerned with "Skeptic clones" so people used the trademark symbol to ridicule him.

**Comment by embray** [comment]
Ah, I didn't know that.  Good deal.

**Comment by iguananaut** [comment]
Ah, I didn't know about that.  Good deal.  I think I will make just a small change to make the TM somewhat random, so it's a bonus when it's there.

**Comment by iguananaut** [comment]
Nice, got "Mr Opinions 1™" after merging this.

**Pull request merged**
